### ISSUE TITLE
Incompatible with Go 1.23, which doesn't allow //go:linkname to internal symbols, including to runtime package

### ISSUE THREAD

**Issue by stefanb** [tickstep/library-go#1]
While testing Go 1.23 rc1 in 
* https://github.com/Homebrew/homebrew-core/pull/175310
 
there was an error:
````
  # github.com/tickstep/aliyunpan
  link: github.com/tickstep/library-go/cachepool: invalid reference to runtime.rawbyteslice
````

Go 1.23 no longer allows `//go:linkname * runtime.*` link instructioins, see 
* https://tip.golang.org/doc/go1.23#linker
* https://github.com/golang/go/issues/67401

It is used in
https://github.com/tickstep/library-go/blob/49613680e69f5fa832a5ea0b13dc68b58e9000a8/cachepool/malloc.go#L12C3-L18

**Comment by stefanb** [comment]
Still failing with Go 1.23rc2

**Comment by tickstep** [comment]
fix it in the latest verison
